
name: programmer_life_game
description: A browser-based game that simulates the life of a programmer.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/workplace_idle.png
    - assets/images/workplace_coding.png
    - assets/images/workplace_break.png
    - assets/images/breakroom_idle.png
    - assets/images/breakroom_active.png
    - assets/images/conference_room.png
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700